project: test01-100
name: explore 01
description: explore broad
program: train
method: random
metric:
    goal: minimize
    name: train_loss
parameters:


    # # reproducability
    # seed:
    #     value: 33

    # # model
    # model_name:
    #     value: RecurrenceModel
    # hidden_units_list:
    #     value: [3,8,3]
    activation_function:
        distribution: categorical
        values:
        - elu
        - celu
        - gelu
        - selu
        - relu
        - leaky_relu

    # # train regime
    # optimizer:
    #     value: Adam
    # loss_func:
    #     value: RMSE
    learning_rate: 
        distribution: uniform
        min: 0.01  # 0.0227
        max: 0.2  # 0.0235
    weight_decay: 
        distribution: uniform
        min: 0.001
        max: 0.1
    batch_size:
        # 32 better than 64 better than 128
        values: [8, 16, 32, 64, 128]
        probabilities: [0.15, 0.2, 0.3, 0.2, 0.15]
    epochs:
        distribution: int_uniform
        min: 2
        max: 6
    dataset_size:
        distribution: q_uniform
        min: 2000
        max: 20000
        q: 1000

    # # train data
    # num_samples:
    #     value: 20**3  # 30**3 better than 40**3
    # dataset:  # TODO improve definition of dataset
    #     value: np.random.normal([x:0,30, y:0,30, z:25,25], num_samples)
    # map_name:
    #     value: lorentz_ode
    # parameters:
    #     value: {'sigma': 10, 'beta': 8/3, 'rho': 28, 'dt': 0.01}
    
    # # device
    # device:
    #     value: mps
    # dtype:
    #     value: float32
    # # num_workers:
    # #     value: 4
    # gpu_name:
    #     value: M1Pro GPU 16 Cores
