name: torch-metal
channels:
  - conda-forge
  - defaults
dependencies:
    - python=3.9
    - pip>=19.0
    - jupyter
    - numpy
    - scikit-learn
    - scipy
    - matplotlib
    - seaborn
    - opencv
    - tqdm
    - wandb
    - transformers
    - pip:
        - --pre torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/nightly/cpu
        